/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Visitor as PrismaVisitor,
  Feedback as PrismaFeedback,
  StoreReviews as PrismaStoreReviews,
  Ticket as PrismaTicket,
} from "@prisma/client";

export class VisitorServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.VisitorCountArgs, "select">): Promise<number> {
    return this.prisma.visitor.count(args);
  }

  async visitors(args: Prisma.VisitorFindManyArgs): Promise<PrismaVisitor[]> {
    return this.prisma.visitor.findMany(args);
  }
  async visitor(
    args: Prisma.VisitorFindUniqueArgs
  ): Promise<PrismaVisitor | null> {
    return this.prisma.visitor.findUnique(args);
  }
  async createVisitor(args: Prisma.VisitorCreateArgs): Promise<PrismaVisitor> {
    return this.prisma.visitor.create(args);
  }
  async updateVisitor(args: Prisma.VisitorUpdateArgs): Promise<PrismaVisitor> {
    return this.prisma.visitor.update(args);
  }
  async deleteVisitor(args: Prisma.VisitorDeleteArgs): Promise<PrismaVisitor> {
    return this.prisma.visitor.delete(args);
  }

  async findFeedbacks(
    parentId: string,
    args: Prisma.FeedbackFindManyArgs
  ): Promise<PrismaFeedback[]> {
    return this.prisma.visitor
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .feedbacks(args);
  }

  async findStoreReviewsItems(
    parentId: string,
    args: Prisma.StoreReviewsFindManyArgs
  ): Promise<PrismaStoreReviews[]> {
    return this.prisma.visitor
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .storeReviewsItems(args);
  }

  async findTickets(
    parentId: string,
    args: Prisma.TicketFindManyArgs
  ): Promise<PrismaTicket[]> {
    return this.prisma.visitor
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tickets(args);
  }
}
