/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MaintenanceRequest } from "./MaintenanceRequest";
import { MaintenanceRequestCountArgs } from "./MaintenanceRequestCountArgs";
import { MaintenanceRequestFindManyArgs } from "./MaintenanceRequestFindManyArgs";
import { MaintenanceRequestFindUniqueArgs } from "./MaintenanceRequestFindUniqueArgs";
import { CreateMaintenanceRequestArgs } from "./CreateMaintenanceRequestArgs";
import { UpdateMaintenanceRequestArgs } from "./UpdateMaintenanceRequestArgs";
import { DeleteMaintenanceRequestArgs } from "./DeleteMaintenanceRequestArgs";
import { Space } from "../../space/base/Space";
import { Tenant } from "../../tenant/base/Tenant";
import { MaintenanceRequestService } from "../maintenanceRequest.service";
@graphql.Resolver(() => MaintenanceRequest)
export class MaintenanceRequestResolverBase {
  constructor(protected readonly service: MaintenanceRequestService) {}

  async _maintenanceRequestsMeta(
    @graphql.Args() args: MaintenanceRequestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MaintenanceRequest])
  async maintenanceRequests(
    @graphql.Args() args: MaintenanceRequestFindManyArgs
  ): Promise<MaintenanceRequest[]> {
    return this.service.maintenanceRequests(args);
  }

  @graphql.Query(() => MaintenanceRequest, { nullable: true })
  async maintenanceRequest(
    @graphql.Args() args: MaintenanceRequestFindUniqueArgs
  ): Promise<MaintenanceRequest | null> {
    const result = await this.service.maintenanceRequest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MaintenanceRequest)
  async createMaintenanceRequest(
    @graphql.Args() args: CreateMaintenanceRequestArgs
  ): Promise<MaintenanceRequest> {
    return await this.service.createMaintenanceRequest({
      ...args,
      data: {
        ...args.data,

        space: args.data.space
          ? {
              connect: args.data.space,
            }
          : undefined,

        tenant: args.data.tenant
          ? {
              connect: args.data.tenant,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => MaintenanceRequest)
  async updateMaintenanceRequest(
    @graphql.Args() args: UpdateMaintenanceRequestArgs
  ): Promise<MaintenanceRequest | null> {
    try {
      return await this.service.updateMaintenanceRequest({
        ...args,
        data: {
          ...args.data,

          space: args.data.space
            ? {
                connect: args.data.space,
              }
            : undefined,

          tenant: args.data.tenant
            ? {
                connect: args.data.tenant,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MaintenanceRequest)
  async deleteMaintenanceRequest(
    @graphql.Args() args: DeleteMaintenanceRequestArgs
  ): Promise<MaintenanceRequest | null> {
    try {
      return await this.service.deleteMaintenanceRequest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Space, {
    nullable: true,
    name: "space",
  })
  async getSpace(
    @graphql.Parent() parent: MaintenanceRequest
  ): Promise<Space | null> {
    const result = await this.service.getSpace(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Tenant, {
    nullable: true,
    name: "tenant",
  })
  async getTenant(
    @graphql.Parent() parent: MaintenanceRequest
  ): Promise<Tenant | null> {
    const result = await this.service.getTenant(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
