/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  LeaseAgreement as PrismaLeaseAgreement,
  Space as PrismaSpace,
  Tenant as PrismaTenant,
} from "@prisma/client";

export class LeaseAgreementServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.LeaseAgreementCountArgs, "select">
  ): Promise<number> {
    return this.prisma.leaseAgreement.count(args);
  }

  async leaseAgreements(
    args: Prisma.LeaseAgreementFindManyArgs
  ): Promise<PrismaLeaseAgreement[]> {
    return this.prisma.leaseAgreement.findMany(args);
  }
  async leaseAgreement(
    args: Prisma.LeaseAgreementFindUniqueArgs
  ): Promise<PrismaLeaseAgreement | null> {
    return this.prisma.leaseAgreement.findUnique(args);
  }
  async createLeaseAgreement(
    args: Prisma.LeaseAgreementCreateArgs
  ): Promise<PrismaLeaseAgreement> {
    return this.prisma.leaseAgreement.create(args);
  }
  async updateLeaseAgreement(
    args: Prisma.LeaseAgreementUpdateArgs
  ): Promise<PrismaLeaseAgreement> {
    return this.prisma.leaseAgreement.update(args);
  }
  async deleteLeaseAgreement(
    args: Prisma.LeaseAgreementDeleteArgs
  ): Promise<PrismaLeaseAgreement> {
    return this.prisma.leaseAgreement.delete(args);
  }

  async getSpace(parentId: string): Promise<PrismaSpace | null> {
    return this.prisma.leaseAgreement
      .findUnique({
        where: { id: parentId },
      })
      .space();
  }

  async getTenant(parentId: string): Promise<PrismaTenant | null> {
    return this.prisma.leaseAgreement
      .findUnique({
        where: { id: parentId },
      })
      .tenant();
  }
}
