/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Mall } from "./Mall";
import { MallCountArgs } from "./MallCountArgs";
import { MallFindManyArgs } from "./MallFindManyArgs";
import { MallFindUniqueArgs } from "./MallFindUniqueArgs";
import { DeleteMallArgs } from "./DeleteMallArgs";
import { MallService } from "../mall.service";
@graphql.Resolver(() => Mall)
export class MallResolverBase {
  constructor(protected readonly service: MallService) {}

  async _mallsMeta(
    @graphql.Args() args: MallCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Mall])
  async malls(@graphql.Args() args: MallFindManyArgs): Promise<Mall[]> {
    return this.service.malls(args);
  }

  @graphql.Query(() => Mall, { nullable: true })
  async mall(@graphql.Args() args: MallFindUniqueArgs): Promise<Mall | null> {
    const result = await this.service.mall(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Mall)
  async deleteMall(@graphql.Args() args: DeleteMallArgs): Promise<Mall | null> {
    try {
      return await this.service.deleteMall(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
