/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, IsEnum, ValidateNested } from "class-validator";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { StringFilter } from "../../util/StringFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { EnumFeedbackResponseStatus } from "./EnumFeedbackResponseStatus";
import { VisitorWhereUniqueInput } from "../../visitor/base/VisitorWhereUniqueInput";

@InputType()
class FeedbackWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  comments?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  date?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  feedbackId?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  rating?: IntNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumFeedbackResponseStatus,
  })
  @IsEnum(EnumFeedbackResponseStatus)
  @IsOptional()
  @Field(() => EnumFeedbackResponseStatus, {
    nullable: true,
  })
  responseStatus?: "Option1";

  @ApiProperty({
    required: false,
    type: () => VisitorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VisitorWhereUniqueInput)
  @IsOptional()
  @Field(() => VisitorWhereUniqueInput, {
    nullable: true,
  })
  visitor?: VisitorWhereUniqueInput;
}

export { FeedbackWhereInput as FeedbackWhereInput };
